version: '6.0.6'

services:

  mongo:
    image: mongo
    restart: always
    container_name: test-mongo
    hostname: host-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345
    volumes:
      - ./data:/data/db
      - ./data/log:/var/log/mongodb/
    ports:
      - "27017:27017"

