version: "3"

services:
  pythonapp:
    container_name: pythonservice
    # restart: always
    build: .
    ports:
      - "5000:3000"
    links:
      - mongodb

  mongodb:
    container_name: mongodatabase
    image:  mongo
    ports:
      - "27018:27017"

#  docker-compose build   image creation with compose
# docker-compose up --build       start services
